services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules:cached
      - pnpm-store:/app/.pnpm-store:cached
    ports:
      - "3000:3000"
      - "6006:6006"
    tty: true

volumes:
  node_modules:
    driver: local
  pnpm-store:
    driver: local
